### ISSUE TITLE
Call for Mentors: NodeSchool Kids Barcelona, January 16, 2016

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#12]
We're going to host a special NodeSchool event for kids and teenagers in Barcelona in collaboration with [MOB](http://www.mob-barcelona.com).

Date: Saturday, January 16th, 2016
Time: 09.30 - 14.00

Volunteers needed: 6-8

If you can commit to this event leave a comment on this issue. I'll update this list as we get more mentors.

Special requirements:
- fluent Catalan and Spanish
### Mentors:
- [x] @axeltaylor 
- [x] @steffen 
- [x] @javiertejero 
- [x] @minitapas 
- [ ] @juliancheal ?
- [x] @danywalls
- [x] @oriolpuig
### Organisers
- [x] @barcelonajs
- [x] @patrickheneise

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by axeltaylor** [comment]
I may be interested, but I need to know the date before commiting

**Comment by javiertejero** [comment]
What is the recommended age? Any required previous skills? I might be also interested as a mentor.

**Comment by PatrickHeneise** [comment]
@axeltaylor January 16, 2016

@javiertejero 12 to 17 yo

**Comment by axeltaylor** [comment]
@PatrickHeneise It's okay for me! date added to my calendar.

**Comment by steffen** [comment]
I would give it a try as a mentor. Can't speak Catalan, but my Spanish should suffice.

**Comment by PatrickHeneise** [comment]
@juliancheal you're up for some cool robot stuff? And Tessels2's?

**Comment by pchiwan** [comment]
I'm up for this! :D

**Comment by juliancheal** [comment]
@PatrickHeneise YES!!!!1111

**Comment by PatrickHeneise** [comment]
@juliancheal how can we make it happen?

**Comment by minitapas** [comment]
gladly!

**Comment by minitapas** [comment]
Hey

I would gladly volunteer.
I speak fluent Spanish and intermediate Catalan, and generally am quite
agile with computers and some programming languages.

Cheers,

Nico

**Comment by lpallares** [comment]
I'm in!

**Comment by danywalls** [comment]
Hi @PatrickHeneise , I'm fluent spanish but my catalan is "undefined", but i can help :+1:

**Comment by PatrickHeneise** [comment]
:+1:

**Comment by oriolpuig** [comment]
Hii @PatrickHeneise, I would like to help on this adventure. Could I? :tada:

**Comment by PatrickHeneise** [comment]
Of course, all help is welcome!

**Comment by minitapas** [comment]
Hey do we know yet where the event is taking place?

**Comment by danywalls** [comment]
@minitapas [here](https://ti.to/barcelonajs/barcelonajs-jan-2016) you can see all informaction about event.

**Comment by PatrickHeneise** [comment]
NodeSchool Barcelona has now it's own ti.to team: https://ti.to/nodeschool-barcelona

**Comment by pchiwan** [comment]
Hello all @minitapas @oriolpuig @axeltaylor @steffen @javiertejero @lpallares @danywalls 
The event is happening this Saturday 16/01 and we need volunteers to register for it! 
All of you who already expressed their intention to join in as mentors and are still available, please head to [the event page on ti.to](https://ti.to/nodeschool-barcelona/nodeschool-kids) and register for a mentor ticket (there are 4 tickets left).

Once I know who's coming and who's not, we should get together if only briefly to discuss what everyone's tasks will be during the workshop. This meeting should be held either next Thursday or Friday, so please help me plan in advance by responding with your availability.

Thanks!

**Comment by danywalls** [comment]
@pchiwan done ! :+1:

**Comment by axeltaylor** [comment]
@pchiwan I'm free on Friday afternoon

**Comment by oriolpuig** [comment]
@pchiwan I'm ready and free this two days.

**Comment by danywalls** [comment]
@pchiwan I'm available on friday afternoon over 6:00 pm, but create we can create a doodle for availability.

**Comment by pchiwan** [comment]
Hey all @danywalls @oriolpuig @axeltaylor thanks for your quick replies and registering your mentor tickets! Along with @ifraixedes and myself that makes 5 mentors for Saturday Vs. 14 attendees, hopefully some more will be registering between today and tomorrow. 

Ok so **let's have a brief meeting on Friday 15th** since we're all available then. If it's ok with you all **let's meet at [Blacklab Brewhouse](http://www.blacklab.es/) (next to metro L4 Barceloneta) at 19h**, @PatrickHeneise might be available to join as well.

In the meantime you might want to have a look at [Johnny Five](http://johnny-five.io/), a JavaScript programming framework that's compatible with a wide range of platforms. Ideally we'll get into that on Saturday.

See ya! ;)

**Comment by minitapas** [comment]
Count me in for Friday!

**Comment by pchiwan** [comment]
Hey @minitapas, cool! If you still can also make it on Saturday there's 1 mentor ticket remaining at [ti.to](https://ti.to/nodeschool-barcelona/nodeschool-kids), go get it! :)

**Comment by ifraixedes** [comment]
Hey, sorry for my delayed response.

Unfortunately, I cannot make on Friday I have another meeting for another event just before but I have to catch up some work, so taking that time for that and be available for Saturday as I've have it in my planning for more than 1 month ago.

**Comment by pchiwan** [comment]
No problem @ifraixedes see you on Saturday at MOB! ;)

**Comment by javiertejero** [comment]
@pchiwan Hi, not sure if I will be able to make it. Also, I am out of town today, so in the best case see you all around Saturday morning. There are no mentor tickets available anyway :) so I assume we have a good mentor to assistant ratio at the moment?

Apologies for the late notice.

**Comment by danywalls** [comment]
@pchiwan  unfortunately i cannot join today on the meeting, for unexpected personal issue, i'm sorry  @axeltaylor @oriolpuig will be explain more details.

**Comment by pchiwan** [comment]
Hey all! Soooo now the first Nodeschool Kids is behind us, here are my thoughts about it:

First and foremost, thank you VERY much @danywalls @axeltaylor @oriolpuig and @ifraixedes for joining as mentors, and for your easygoingness and predisposition. It was great to meet you, you guys are cool! :smiley: 

I have to admit I was very worried during the past 4 weeks about the outcome of the event. Mainly I was concerned that we would not meet the expectations of our attendees because none of us knew anything about robots (nor Arduinos), and we actually didn't have any _real robots_ to play with! The _javascripting_ workshopper was a lifesaver: it kept the kids occupied for most of the workshop. Ultimately I brought my dumb Roomba and the kids got to play with it a bit and they seemed to enjoy it; so at least they couldn't say they didn't program any robots! So, given the situation, I think the event came out pretty well and the overall feedback was positive.

Some notes for our future selves regarding next Nodeschool Kids events:
- It would be awesome if we manage to get Julian to come and bring his toys. But we should arrange a date with him and then organize the event accordingly, not the other way around.
- When -if- we do this again -with or without Julian- we should find people who have experience with microcontrollers and who could lead the event and teach us some stuff in advance, in preparation for it.
- We should promote it more and through more channels: only 7 attendees showed up! 
- Cecilia from MOB showed up and told us they can provide us with anything we may need for our workshops, we just need to tell them in advance.
- Remember to tell attendees to brings their laptops! :sweat_smile: 

(**Please feel free to comment and add your own thoughts.**)

I'm relieved that my first time as an event organizer wasn't a complete disaster. For sure I've learnt quite a few things from this experience. 

Thank you all again! :smiley:

**Comment by lcrespom** [comment]
Hi! Here is my feedback:
- First, many thanks to all organizers for donating their time for this great non-profit activity.
- The iRobot part was very fun - too bad the Arduinos were not setup. I have some Arduino experience, call me next time and I may be able to provide help.
- I think the javascripting interactive course is, well, not very good. I would greatly modify that part either by replacing it with some other course or just having more teacher-led sessions. I think there are two main problems with the current javascripting course:
  - Its is partially translated, resulting in great inconsistencies between the expected and actual output.
  - Concepts are introduced too lightly, so totally novice kids end up just copying code without really understanding what is going on.

**Comment by oriolpuig** [comment]
First of all, thanks to NodeSchool to allows me be part of the first NodeSchoolKids.
I think is a good initiative and we should write more chapters!

Then, things I think we should improve: 
- Mention in the event info, the attendees should bring their laptops.
- We should talk with some schools where children study development. This will promote the event!
- We should test Arduinos before the event and prepare some tests to show it to the attendees. Roomba saved our lives! (Thanks @pchiwan)

And that's all by my side
